/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analysis {
  'id' : AnalysisId,
  'overallScore' : bigint,
  'tips' : Array<Tip>,
  'resumeText' : string,
  'timestamp' : Timestamp,
  'categoryScores' : CategoryScores,
}
export type AnalysisId = bigint;
export type AnalysisResult = { 'ok' : Analysis } |
  { 'err' : string };
export interface AnalysisSummary {
  'id' : AnalysisId,
  'overallScore' : bigint,
  'snippet' : string,
  'timestamp' : Timestamp,
  'categoryScores' : CategoryScores,
}
export interface CategoryScores {
  'formatting' : bigint,
  'education' : bigint,
  'clarity' : bigint,
  'experience' : bigint,
  'keywords' : bigint,
  'skills' : bigint,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Timestamp = bigint;
export interface Tip {
  'text' : string,
  'category' : string,
  'priority' : Priority,
}
export interface _SERVICE {
  'analyzeResume' : ActorMethod<[string], AnalysisResult>,
  'deleteAnalysis' : ActorMethod<[AnalysisId], boolean>,
  'getAnalysis' : ActorMethod<[AnalysisId], [] | [Analysis]>,
  'listAnalyses' : ActorMethod<[], Array<AnalysisSummary>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];