/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnalysisId = IDL.Nat;
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Tip = IDL.Record({
  'text' : IDL.Text,
  'category' : IDL.Text,
  'priority' : Priority,
});
export const Timestamp = IDL.Int;
export const CategoryScores = IDL.Record({
  'formatting' : IDL.Nat,
  'education' : IDL.Nat,
  'clarity' : IDL.Nat,
  'experience' : IDL.Nat,
  'keywords' : IDL.Nat,
  'skills' : IDL.Nat,
});
export const Analysis = IDL.Record({
  'id' : AnalysisId,
  'overallScore' : IDL.Nat,
  'tips' : IDL.Vec(Tip),
  'resumeText' : IDL.Text,
  'timestamp' : Timestamp,
  'categoryScores' : CategoryScores,
});
export const AnalysisResult = IDL.Variant({
  'ok' : Analysis,
  'err' : IDL.Text,
});
export const AnalysisSummary = IDL.Record({
  'id' : AnalysisId,
  'overallScore' : IDL.Nat,
  'snippet' : IDL.Text,
  'timestamp' : Timestamp,
  'categoryScores' : CategoryScores,
});

export const idlService = IDL.Service({
  'analyzeResume' : IDL.Func([IDL.Text], [AnalysisResult], []),
  'deleteAnalysis' : IDL.Func([AnalysisId], [IDL.Bool], []),
  'getAnalysis' : IDL.Func([AnalysisId], [IDL.Opt(Analysis)], ['query']),
  'listAnalyses' : IDL.Func([], [IDL.Vec(AnalysisSummary)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnalysisId = IDL.Nat;
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Tip = IDL.Record({
    'text' : IDL.Text,
    'category' : IDL.Text,
    'priority' : Priority,
  });
  const Timestamp = IDL.Int;
  const CategoryScores = IDL.Record({
    'formatting' : IDL.Nat,
    'education' : IDL.Nat,
    'clarity' : IDL.Nat,
    'experience' : IDL.Nat,
    'keywords' : IDL.Nat,
    'skills' : IDL.Nat,
  });
  const Analysis = IDL.Record({
    'id' : AnalysisId,
    'overallScore' : IDL.Nat,
    'tips' : IDL.Vec(Tip),
    'resumeText' : IDL.Text,
    'timestamp' : Timestamp,
    'categoryScores' : CategoryScores,
  });
  const AnalysisResult = IDL.Variant({ 'ok' : Analysis, 'err' : IDL.Text });
  const AnalysisSummary = IDL.Record({
    'id' : AnalysisId,
    'overallScore' : IDL.Nat,
    'snippet' : IDL.Text,
    'timestamp' : Timestamp,
    'categoryScores' : CategoryScores,
  });
  
  return IDL.Service({
    'analyzeResume' : IDL.Func([IDL.Text], [AnalysisResult], []),
    'deleteAnalysis' : IDL.Func([AnalysisId], [IDL.Bool], []),
    'getAnalysis' : IDL.Func([AnalysisId], [IDL.Opt(Analysis)], ['query']),
    'listAnalyses' : IDL.Func([], [IDL.Vec(AnalysisSummary)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };